### ISSUE TITLE
Sinister Strike doesn't generate combo points unless you learn Eviscerate

### ISSUE THREAD

**Issue by Drakeare** [Project-Deus/Deus-Classless-Issues#70] opened 2021-12-22 21:31 UTC
Sinister strike doesn't generate any combo points unless eviscerate is learned. Even if you unlearn Eviscerate, you lose the ability to generate combo points

**Comment by Blandmarrow** [comment] 2021-12-23 08:11
Duplicate of https://github.com/Project-Deus/Deus-Classless-Issues/issues/51

**Closed by Blandmarrow** 2021-12-23 08:11 UTC
Labels: duplicate
