### ISSUE TITLE
Sinister Strike procs Overpower

### ISSUE THREAD

**Issue by Blandmarrow** [Project-Deus/Deus-Classless-Issues#120] opened 2021-12-28 20:13 UTC
**Describe the bug**
Sinister Strike procs Overpower.

**To Reproduce**
1. Pick Overpower & Sinister Strike
2. Cast Sinister Strike
3. Overpower procs

**Expected behavior**
Overpower should not be procced by sinister strike

**Screenshots**

**Additional context**
IDs:
Sinister Strike: 1752
Overpower: 7384

**Comment by Drakeare** [comment] 2021-12-29 23:05
Seems like Overpower also procs from Garrote. SpellID: 703

**Comment by UltraNix** [comment] 2022-11-15 10:53
Duplicate of #117

**Closed by UltraNix** 2022-11-15 10:53 UTC
Labels: Bug, Working on
